### ISSUE TITLE
optionally add metadata to ABFConvert and DATConvert.

### ISSUE THREAD

**Issue by bendichter** [AllenInstitute/ipfx#399]
It would be nice to be able to add metadata to the `run_x_to_nwb_conversion.py` command. In [nwb-conversion-tools](https://github.com/catalystneuro/nwb-conversion-tools/), we handle this with a YAML file that turns into a hierarchical `dict`. For instance, you could supply a YAML file of the form:

```yaml
NWBFile:
  session_id: '00003'
  session_description: 'Description of session'
Subject:
  subject_id: '0001'
  age: '30 days'
```
`run_x_to_nwb_conversion.py` would turn that YAML file into a `dict` and and then `ABFConverter` and `DATConverter` would take that dict and populate the NWB file accordingly.

This relates to #364 as well. pynwb acts more straightforwardly if you can write all of the metadata in the initial write. It would be better to specify the subject ID during the creation of the file rather than  write it in after-the-fact.
